name: Actualizar Datos COVID

on:
  schedule:
    - cron: '0 0 * * *'   # Cada día a medianoche UTC
  workflow_dispatch:      # Permite ejecutarlo manualmente

jobs:
  update-data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repositorio
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Instalar dependencias
        run: pip install -r requirements.txt

      - name: Ejecutar extracción de datos
        run: python src/data_extraction.py

      - name: Subir cambios al repositorio
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add .
          git commit -m "📥 Datos actualizados automáticamente"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
